// Generated by gencpp from file uthai_nav/GetViaPoint.msg
// DO NOT EDIT!


#ifndef UTHAI_NAV_MESSAGE_GETVIAPOINT_H
#define UTHAI_NAV_MESSAGE_GETVIAPOINT_H

#include <ros/service_traits.h>


#include <uthai_nav/GetViaPointRequest.h>
#include <uthai_nav/GetViaPointResponse.h>


namespace uthai_nav
{

struct GetViaPoint
{

typedef GetViaPointRequest Request;
typedef GetViaPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetViaPoint
} // namespace uthai_nav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uthai_nav::GetViaPoint > {
  static const char* value()
  {
    return "3f8930d968a3e84d471dff917bb1cdae";
  }

  static const char* value(const ::uthai_nav::GetViaPoint&) { return value(); }
};

template<>
struct DataType< ::uthai_nav::GetViaPoint > {
  static const char* value()
  {
    return "uthai_nav/GetViaPoint";
  }

  static const char* value(const ::uthai_nav::GetViaPoint&) { return value(); }
};


// service_traits::MD5Sum< ::uthai_nav::GetViaPointRequest> should match 
// service_traits::MD5Sum< ::uthai_nav::GetViaPoint > 
template<>
struct MD5Sum< ::uthai_nav::GetViaPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uthai_nav::GetViaPoint >::value();
  }
  static const char* value(const ::uthai_nav::GetViaPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uthai_nav::GetViaPointRequest> should match 
// service_traits::DataType< ::uthai_nav::GetViaPoint > 
template<>
struct DataType< ::uthai_nav::GetViaPointRequest>
{
  static const char* value()
  {
    return DataType< ::uthai_nav::GetViaPoint >::value();
  }
  static const char* value(const ::uthai_nav::GetViaPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uthai_nav::GetViaPointResponse> should match 
// service_traits::MD5Sum< ::uthai_nav::GetViaPoint > 
template<>
struct MD5Sum< ::uthai_nav::GetViaPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uthai_nav::GetViaPoint >::value();
  }
  static const char* value(const ::uthai_nav::GetViaPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uthai_nav::GetViaPointResponse> should match 
// service_traits::DataType< ::uthai_nav::GetViaPoint > 
template<>
struct DataType< ::uthai_nav::GetViaPointResponse>
{
  static const char* value()
  {
    return DataType< ::uthai_nav::GetViaPoint >::value();
  }
  static const char* value(const ::uthai_nav::GetViaPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UTHAI_NAV_MESSAGE_GETVIAPOINT_H
